/**
 * Granny's Money Corner — scenario bank.
 * Zero-API-cost by design: everything below is static data, selected
 * client-side. No LLM calls, no server round-trip required to play.
 *
 * Adding scenarios: append to SCENARIOS below, following the
 * GrannyScenario shape exactly (3-4 choices, one with isGrannyPick:
 * true). Nothing else in the app needs to change — the widget and the
 * date picker both just read from this array. Aim for 40-60 at launch;
 * scenario copy is written by hand, not generated.
 */

export type GrannyCategory =
  | "savings"
  | "debt"
  | "impulse"
  | "emergency"
  | "social";

export type GrannyDifficulty = "easy" | "medium" | "hard";

/** The four character stats a Granny Score is built from. Keep this list
 *  fixed — it's what "Your financial character" bars are drawn from. */
export interface GrannyEffects {
  savingsDiscipline: number; // -10..+15
  impulseControl: number; // -10..+15
  debtManagement: number; // -10..+15
  budgeting: number; // -10..+15
}

export interface GrannyChoice {
  /** stable id within this scenario, e.g. "a" | "b" | "c" | "d" */
  id: string;
  /** short label shown on the button, e.g. "Go for dinner" */
  label: string;
  /** single emoji, used as the button's visual anchor */
  emoji: string;
  /** £ amount this choice costs (0 for "save it" / free options) */
  cost: number;
  /** true for the one choice Granny would make — drives her tone,
   *  never blocks or scolds the other options */
  isGrannyPick: boolean;
  /** score deltas applied when this choice is picked */
  effects: GrannyEffects;
  /** Granny's in-voice reaction, shown after this specific choice.
   *  Keep it warm, never scolding — even the "wrong" picks get a kind,
   *  honest response, not a lecture. */
  response: string;
}

export interface GrannyScenario {
  id: string; // e.g. "2026-08-27" or a stable slug like "s014-dinner-invite"
  category: GrannyCategory;
  difficulty: GrannyDifficulty;
  /** the £-until-payday framing line, e.g. "You've got £180 left until payday." */
  setupLine: string;
  /** the dilemma itself, e.g. "Your friend invites you out for dinner." */
  situation: string;
  choices: GrannyChoice[]; // 3-4 entries
}

/** ---- Scenario bank ---- */

export const SCENARIOS: GrannyScenario[] = [
  {
    id: "s001-dinner-invite",
    category: "social",
    difficulty: "easy",
    setupLine: "You've got £180 left until payday.",
    situation:
      "Your friend invites you out for dinner. You'd also promised yourself you'd put £50 towards savings this month.",
    choices: [
      {
        id: "a",
        label: "Go for dinner",
        emoji: "🍝",
        cost: 45,
        isGrannyPick: false,
        effects: { savingsDiscipline: -4, impulseControl: -6, debtManagement: 0, budgeting: -2 },
        response:
          "Fair enough — nobody should skip every dinner out. Just make sure next month's £50 makes up for it.",
      },
      {
        id: "b",
        label: "Buy the shoes instead",
        emoji: "👟",
        cost: 70,
        isGrannyPick: false,
        effects: { savingsDiscipline: -6, impulseControl: -10, debtManagement: 0, budgeting: -4 },
        response:
          "New shoes are lovely. £70 lovely, with £50 of savings still unpaid? That's the bit worth noticing.",
      },
      {
        id: "c",
        label: "Put £50 into savings",
        emoji: "💰",
        cost: 50,
        isGrannyPick: true,
        effects: { savingsDiscipline: 12, impulseControl: 6, debtManagement: 0, budgeting: 8 },
        response: "I'd keep the £50. Future you will thank you.",
      },
      {
        id: "d",
        label: "Keep it for emergencies",
        emoji: "🛟",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 4, impulseControl: 8, debtManagement: 2, budgeting: 6 },
        response:
          "Sensible, and I won't argue with a cushion. Though a *named* goal tends to get funded faster than a vague one.",
      },
    ],
  },
  {
    id: "s002-washing-machine",
    category: "emergency",
    difficulty: "medium",
    setupLine: "You've got £320 left this month, and no wiggle room until payday.",
    situation: "Your washing machine has just died.",
    choices: [
      {
        id: "a",
        label: "Pay for a repair",
        emoji: "🔧",
        cost: 65,
        isGrannyPick: true,
        effects: { savingsDiscipline: 4, impulseControl: 6, debtManagement: 4, budgeting: 10 },
        response:
          "A repair first, replace only if it fails again — that's how you keep emergencies from becoming disasters.",
      },
      {
        id: "b",
        label: "Replace it outright",
        emoji: "🧺",
        cost: 320,
        isGrannyPick: false,
        effects: { savingsDiscipline: -12, impulseControl: -8, debtManagement: -6, budgeting: -10 },
        response:
          "Sometimes a full replacement really is right — but at £320 against a £320 budget, you've spent the whole month on one machine.",
      },
      {
        id: "c",
        label: "Ask a friend to help fix it",
        emoji: "🤝",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 6, impulseControl: 2, debtManagement: 2, budgeting: 4 },
        response:
          "Free help is a gift, not a right — just don't let it become the whole plan for next time too.",
      },
    ],
  },
  {
    id: "s003-colleague-lunch",
    category: "impulse",
    difficulty: "easy",
    setupLine: "You've got £62 left until payday, four days away.",
    situation: "A colleague suggests lunch out.",
    choices: [
      {
        id: "a",
        label: "Restaurant",
        emoji: "🍽️",
        cost: 12,
        isGrannyPick: false,
        effects: { savingsDiscipline: -3, impulseControl: -4, debtManagement: 0, budgeting: -2 },
        response: "One lunch won't ruin you — just notice if 'one lunch' happens most days.",
      },
      {
        id: "b",
        label: "Supermarket meal deal",
        emoji: "🥪",
        cost: 4,
        isGrannyPick: false,
        effects: { savingsDiscipline: 2, impulseControl: 4, debtManagement: 0, budgeting: 4 },
        response: "A perfectly good middle ground. You still got the lunch out with your colleague.",
      },
      {
        id: "c",
        label: "Bring leftovers from home",
        emoji: "🍱",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 8, debtManagement: 0, budgeting: 6 },
        response: "Leftovers win again. Four days to payday, and you've spent nothing on lunch.",
      },
    ],
  },

  {
    id: "s004-birthday-drinks",
    category: "social",
    difficulty: "easy",
    setupLine: "You've got £95 left until payday, five days away.",
    situation: "It's a colleague's birthday and the team's going for a round of drinks after work.",
    choices: [
      {
        id: "a",
        label: "Join for a couple of rounds",
        emoji: "🍻",
        cost: 25,
        isGrannyPick: false,
        effects: { savingsDiscipline: -3, impulseControl: -4, debtManagement: 0, budgeting: -2 },
        response: "A birthday's a birthday — just count it as tonight's whole budget, not a warm-up.",
      },
      {
        id: "b",
        label: "Go, but stick to one drink",
        emoji: "🥂",
        cost: 8,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 8, debtManagement: 0, budgeting: 6 },
        response: "You showed up, you celebrated, and £8 didn't wreck your week. That's the balance.",
      },
      {
        id: "c",
        label: "Skip it and stay in",
        emoji: "🏠",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 4, impulseControl: 6, debtManagement: 0, budgeting: 4 },
        response: "Nothing wrong with staying in — though don't let every invitation become a no. Relationships cost something too.",
      },
    ],
  },
  {
    id: "s005-group-holiday-deposit",
    category: "social",
    difficulty: "medium",
    setupLine: "You've got £430 saved for miscellaneous plans this month.",
    situation: "Friends want to book a group holiday and need a £150 deposit from everyone this week.",
    choices: [
      {
        id: "a",
        label: "Pay the deposit straight away",
        emoji: "✈️",
        cost: 150,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 6, debtManagement: 2, budgeting: 8 },
        response: "If the trip's really happening and you want in, paying early avoids a scramble later. Just make sure the rest of the cost has a plan too.",
      },
      {
        id: "b",
        label: "Put it on a credit card 'for now'",
        emoji: "💳",
        cost: 150,
        isGrannyPick: false,
        effects: { savingsDiscipline: -6, impulseControl: -4, debtManagement: -10, budgeting: -6 },
        response: "Money you have and money you'll 'sort out later' spend very differently. Best to know which one this is before you tap the card.",
      },
      {
        id: "c",
        label: "Ask for two more weeks to decide",
        emoji: "⏳",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 2, impulseControl: 4, debtManagement: 2, budgeting: 2 },
        response: "Fair enough if you genuinely need to check the numbers — just don't let 'two weeks' quietly become 'never decided'.",
      },
    ],
  },
  {
    id: "s006-wedding-gift",
    category: "social",
    difficulty: "easy",
    setupLine: "You've got £210 left this month.",
    situation: "You're invited to a friend's wedding and need to choose a gift.",
    choices: [
      {
        id: "a",
        label: "Big gift off the registry",
        emoji: "🎁",
        cost: 80,
        isGrannyPick: false,
        effects: { savingsDiscipline: -4, impulseControl: -2, debtManagement: 0, budgeting: -4 },
        response: "Generous, and lovely — just check it still leaves room for the rest of the month before you commit to it.",
      },
      {
        id: "b",
        label: "A modest gift within budget",
        emoji: "💐",
        cost: 30,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 6, debtManagement: 0, budgeting: 6 },
        response: "A thoughtful gift doesn't need a big price tag. They'll remember the gesture, not the receipt.",
      },
      {
        id: "c",
        label: "Card only, gift later when you can afford it",
        emoji: "✉️",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 2, impulseControl: 2, debtManagement: 0, budgeting: 2 },
        response: "Perfectly fine — a gift given late and well-chosen beats one rushed just to arrive on time.",
      },
    ],
  },
  {
    id: "s007-uber-split",
    category: "social",
    difficulty: "easy",
    setupLine: "You've got £40 left until payday, two days away.",
    situation: "Your group's splitting an Uber home after a night out, and someone suggests the more expensive comfort option.",
    choices: [
      {
        id: "a",
        label: "Go along with the comfort option",
        emoji: "🚗",
        cost: 12,
        isGrannyPick: false,
        effects: { savingsDiscipline: -2, impulseControl: -4, debtManagement: 0, budgeting: -2 },
        response: "It's a small enough amount, but notice how easily you agreed to spend more just to avoid the conversation.",
      },
      {
        id: "b",
        label: "Suggest the standard option instead",
        emoji: "🚕",
        cost: 7,
        isGrannyPick: true,
        effects: { savingsDiscipline: 4, impulseControl: 6, debtManagement: 0, budgeting: 4 },
        response: "Speaking up saved everyone a few pounds, not just you. That's worth doing more often.",
      },
      {
        id: "c",
        label: "Take public transport instead",
        emoji: "🚌",
        cost: 3,
        isGrannyPick: false,
        effects: { savingsDiscipline: 6, impulseControl: 8, debtManagement: 0, budgeting: 6 },
        response: "Cheapest and you got home fine. Just weigh that against the time and safety of the hour.",
      },
    ],
  },
  {
    id: "s008-housewarming-gift",
    category: "social",
    difficulty: "easy",
    setupLine: "You've got £150 left this month.",
    situation: "A friend's just moved into a new flat and invited you to their housewarming.",
    choices: [
      {
        id: "a",
        label: "Bring an expensive gift",
        emoji: "🏠",
        cost: 40,
        isGrannyPick: false,
        effects: { savingsDiscipline: -4, impulseControl: -2, debtManagement: 0, budgeting: -4 },
        response: "A generous gesture — just check it's generosity and not guilt doing the spending.",
      },
      {
        id: "b",
        label: "Bring a bottle of wine and a card",
        emoji: "🍷",
        cost: 12,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 6, debtManagement: 0, budgeting: 6 },
        response: "Turning up matters more than what you carry through the door.",
      },
      {
        id: "c",
        label: "Skip the gift, bring yourself",
        emoji: "🙋",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 2, impulseControl: 2, debtManagement: 0, budgeting: 2 },
        response: "Nobody will mind, though a small something is a nice habit to keep for the ones you're closest to.",
      },
    ],
  },
  {
    id: "s009-leaving-collection",
    category: "social",
    difficulty: "medium",
    setupLine: "You've got £75 left until payday, six days away.",
    situation: "A colleague you don't know well is leaving, and there's a collection going round for a gift.",
    choices: [
      {
        id: "a",
        label: "Put in what everyone else seems to be putting in",
        emoji: "💷",
        cost: 15,
        isGrannyPick: false,
        effects: { savingsDiscipline: -2, impulseControl: -4, debtManagement: 0, budgeting: -2 },
        response: "Peer pressure spends your money just as fast as an advert does. Worth noticing which one this was.",
      },
      {
        id: "b",
        label: "Give a smaller amount that's honest for you",
        emoji: "🪙",
        cost: 5,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 8, debtManagement: 0, budgeting: 6 },
        response: "You don't need to match anyone else's number. What matters is that you gave something sincerely.",
      },
      {
        id: "c",
        label: "Sign the card, skip the money",
        emoji: "✍️",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 4, impulseControl: 6, debtManagement: 0, budgeting: 4 },
        response: "Nobody's counting who gave what. A kind message costs nothing and still means something.",
      },
    ],
  },
  {
    id: "s010-hen-do",
    category: "social",
    difficulty: "hard",
    setupLine: "You've got £320 left this month, and rent's due in two weeks.",
    situation: "You're invited on a hen do that'll cost roughly £180 all in — activities, accommodation, one big meal out.",
    choices: [
      {
        id: "a",
        label: "Say yes and figure it out later",
        emoji: "🎉",
        cost: 180,
        isGrannyPick: false,
        effects: { savingsDiscipline: -10, impulseControl: -6, debtManagement: -8, budgeting: -10 },
        response: "Saying yes felt good in the moment. Just be honest with yourself about whether rent was actually covered when you said it.",
      },
      {
        id: "b",
        label: "Say yes, but ask about a payment plan",
        emoji: "📅",
        cost: 180,
        isGrannyPick: true,
        effects: { savingsDiscipline: 4, impulseControl: 6, debtManagement: 4, budgeting: 6 },
        response: "Asking felt awkward, I'm sure — but spreading it over a few paydays is exactly the kind of planning that keeps a fun weekend from becoming a stressful month.",
      },
      {
        id: "c",
        label: "Decline this time",
        emoji: "🙏",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 8, impulseControl: 6, debtManagement: 6, budgeting: 8 },
        response: "A hard message to send, but rent not being at risk is worth more than one weekend, even a good one.",
      },
    ],
  },
  {
    id: "s011-fundraiser-ticket",
    category: "social",
    difficulty: "easy",
    setupLine: "You've got £110 left this month.",
    situation: "A friend's running a charity fundraiser and asks if you'll buy a £25 ticket.",
    choices: [
      {
        id: "a",
        label: "Buy the ticket without checking your budget",
        emoji: "🎫",
        cost: 25,
        isGrannyPick: false,
        effects: { savingsDiscipline: -4, impulseControl: -2, debtManagement: 0, budgeting: -4 },
        response: "A good cause, and I won't argue with the reason — just make a habit of checking first, not after.",
      },
      {
        id: "b",
        label: "Check your budget, then buy it",
        emoji: "✅",
        cost: 25,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 6, debtManagement: 0, budgeting: 6 },
        response: "Same money spent, same good cause supported — but you actually knew you could afford it. That's the whole difference.",
      },
      {
        id: "c",
        label: "Donate what you can afford instead",
        emoji: "💝",
        cost: 10,
        isGrannyPick: false,
        effects: { savingsDiscipline: 4, impulseControl: 4, debtManagement: 0, budgeting: 4 },
        response: "A smaller amount, honestly given, is worth just as much as the ticket price to the cause.",
      },
    ],
  },
  {
    id: "s012-family-sunday-lunch",
    category: "social",
    difficulty: "easy",
    setupLine: "You've got £58 left until payday, three days away.",
    situation: "Family suggests Sunday lunch out at a restaurant instead of cooking at home.",
    choices: [
      {
        id: "a",
        label: "Go along with it",
        emoji: "🍽️",
        cost: 22,
        isGrannyPick: false,
        effects: { savingsDiscipline: -3, impulseControl: -2, debtManagement: 0, budgeting: -3 },
        response: "Family time matters — just notice this is most of what's left for the next three days.",
      },
      {
        id: "b",
        label: "Suggest cooking together at home instead",
        emoji: "🍳",
        cost: 8,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 6, debtManagement: 0, budgeting: 6 },
        response: "Same family time, a fraction of the cost, and honestly — probably a better meal.",
      },
      {
        id: "c",
        label: "Go, but order the cheapest thing on the menu",
        emoji: "🥗",
        cost: 12,
        isGrannyPick: false,
        effects: { savingsDiscipline: 2, impulseControl: 2, debtManagement: 0, budgeting: 2 },
        response: "A reasonable middle ground if the outing itself matters more than the meal.",
      },
    ],
  },
  {
    id: "s013-nieces-birthday",
    category: "social",
    difficulty: "medium",
    setupLine: "You've got £140 left this month.",
    situation: "Your niece's birthday is coming up and she's been asking for the latest games console accessory.",
    choices: [
      {
        id: "a",
        label: "Buy exactly what she asked for",
        emoji: "🎮",
        cost: 60,
        isGrannyPick: false,
        effects: { savingsDiscipline: -6, impulseControl: -2, debtManagement: 0, budgeting: -6 },
        response: "She'll be thrilled, no doubt. Just check the rest of the month can absorb it before you commit.",
      },
      {
        id: "b",
        label: "Get something thoughtful within a smaller budget",
        emoji: "🎈",
        cost: 25,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 6, debtManagement: 0, budgeting: 6 },
        response: "Children remember being thought of far more than the price tag. This still does that.",
      },
      {
        id: "c",
        label: "Ask her parents what she actually needs",
        emoji: "👨‍👩‍👧",
        cost: 20,
        isGrannyPick: false,
        effects: { savingsDiscipline: 6, impulseControl: 4, debtManagement: 0, budgeting: 6 },
        response: "A sensible check — avoids duplicate gifts and gets you something genuinely useful to her.",
      },
    ],
  },
  {
    id: "s014-flash-sale-email",
    category: "impulse",
    difficulty: "easy",
    setupLine: "You've got £95 left this month.",
    situation: "An email lands: '24 hours only — 40% off everything', for a shop you like but weren't planning to buy from.",
    choices: [
      {
        id: "a",
        label: "Buy something because the discount is good",
        emoji: "🛍️",
        cost: 35,
        isGrannyPick: false,
        effects: { savingsDiscipline: -6, impulseControl: -10, debtManagement: 0, budgeting: -6 },
        response: "A discount on something you weren't buying anyway isn't really a saving — it's still £35 spent that wasn't in the plan.",
      },
      {
        id: "b",
        label: "Close the email and move on",
        emoji: "📪",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 12, debtManagement: 0, budgeting: 6 },
        response: "The sale will come round again. Your money staying put is the actual win here.",
      },
      {
        id: "c",
        label: "Add it to a wishlist for later",
        emoji: "📝",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 6, impulseControl: 8, debtManagement: 0, budgeting: 4 },
        response: "A good habit — if you still want it in a week, it was worth having. Most things don't survive the wait.",
      },
    ],
  },
  {
    id: "s015-phone-case",
    category: "impulse",
    difficulty: "easy",
    setupLine: "You've got £70 left until payday, four days away.",
    situation: "You spot a phone case online that's 'only £15' and matches your style perfectly.",
    choices: [
      {
        id: "a",
        label: "Buy it on the spot",
        emoji: "📱",
        cost: 15,
        isGrannyPick: false,
        effects: { savingsDiscipline: -3, impulseControl: -6, debtManagement: 0, budgeting: -2 },
        response: "A small purchase, but small purchases are exactly the ones that don't get a second thought — and don't need to be, either.",
      },
      {
        id: "b",
        label: "Wait 24 hours, then decide",
        emoji: "⏰",
        cost: 15,
        isGrannyPick: true,
        effects: { savingsDiscipline: 4, impulseControl: 8, debtManagement: 0, budgeting: 2 },
        response: "If you still want it tomorrow, buy it. Most 'perfect' finds look a lot more optional the next day.",
      },
      {
        id: "c",
        label: "Keep the case you've already got",
        emoji: "🔄",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 6, impulseControl: 8, debtManagement: 0, budgeting: 4 },
        response: "It's already doing the job. That's worth remembering before the next 'perfect' find.",
      },
    ],
  },
  {
    id: "s016-app-subscription",
    category: "impulse",
    difficulty: "easy",
    setupLine: "You've got £88 left this month.",
    situation: "An app you tried once offers a 'special' £4.99/month subscription with a shiny new feature.",
    choices: [
      {
        id: "a",
        label: "Subscribe straight away",
        emoji: "✨",
        cost: 5,
        isGrannyPick: false,
        effects: { savingsDiscipline: -2, impulseControl: -4, debtManagement: 0, budgeting: -4 },
        response: "Five pounds sounds small until it's the fourth 'small' subscription this year, quietly renewing.",
      },
      {
        id: "b",
        label: "Set a reminder to review it in a month",
        emoji: "🔔",
        cost: 5,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 6, debtManagement: 0, budgeting: 8 },
        response: "Trying it isn't the problem — forgetting to cancel is. A reminder is cheap insurance against that.",
      },
      {
        id: "c",
        label: "Skip it entirely",
        emoji: "❌",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 6, impulseControl: 8, debtManagement: 0, budgeting: 4 },
        response: "You've lived without the feature so far. That's usually the honest answer to whether you need it.",
      },
    ],
  },
  {
    id: "s017-late-night-shopping",
    category: "impulse",
    difficulty: "medium",
    setupLine: "You've got £130 left this month.",
    situation: "It's midnight, you can't sleep, and you've got three items sitting in an online basket.",
    choices: [
      {
        id: "a",
        label: "Complete the purchase now",
        emoji: "🌙",
        cost: 45,
        isGrannyPick: false,
        effects: { savingsDiscipline: -8, impulseControl: -12, debtManagement: 0, budgeting: -6 },
        response: "Midnight decisions and daytime decisions are rarely the same decision. Worth noticing which one just happened.",
      },
      {
        id: "b",
        label: "Close the tab and check the basket tomorrow",
        emoji: "🛒",
        cost: 45,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 12, debtManagement: 0, budgeting: 6 },
        response: "If it still makes sense in daylight, it was a good buy all along. If it doesn't, you just saved £45 for the price of one night's patience.",
      },
      {
        id: "c",
        label: "Buy just the cheapest item now",
        emoji: "🏷️",
        cost: 10,
        isGrannyPick: false,
        effects: { savingsDiscipline: 2, impulseControl: 2, debtManagement: 0, budgeting: 2 },
        response: "A compromise — though notice it's still a purchase made at midnight, not a plan.",
      },
    ],
  },
  {
    id: "s018-bogof-deal",
    category: "impulse",
    difficulty: "easy",
    setupLine: "You've got £60 left until payday, five days away.",
    situation: "A 'buy one get one free' deal on something you don't actually need two of.",
    choices: [
      {
        id: "a",
        label: "Buy it for the deal",
        emoji: "🏷️",
        cost: 20,
        isGrannyPick: false,
        effects: { savingsDiscipline: -4, impulseControl: -6, debtManagement: 0, budgeting: -4 },
        response: "Two of something you didn't need one of isn't a bargain — it's spending twice as fast.",
      },
      {
        id: "b",
        label: "Skip it — one wasn't needed either",
        emoji: "🙅",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 10, debtManagement: 0, budgeting: 4 },
        response: "The deal only saves money on things you were already buying. This wasn't one of them.",
      },
      {
        id: "c",
        label: "Buy one, skip the free extra",
        emoji: "1️⃣",
        cost: 20,
        isGrannyPick: false,
        effects: { savingsDiscipline: 0, impulseControl: 2, debtManagement: 0, budgeting: 0 },
        response: "If you genuinely needed one, fair enough — just notice the 'free' half didn't actually save you anything.",
      },
    ],
  },
  {
    id: "s019-trainers-drop",
    category: "impulse",
    difficulty: "medium",
    setupLine: "You've got £180 left this month.",
    situation: "A limited-edition trainer drop goes live at 9am — sold out by lunchtime most times, and they're £120.",
    choices: [
      {
        id: "a",
        label: "Queue up and buy them",
        emoji: "👟",
        cost: 120,
        isGrannyPick: false,
        effects: { savingsDiscipline: -10, impulseControl: -8, debtManagement: 0, budgeting: -10 },
        response: "They're striking, no doubt — just be honest that 'limited edition' is doing most of the persuading here, not the shoes themselves.",
      },
      {
        id: "b",
        label: "Set a budget alert and skip if it's tight",
        emoji: "💷",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 8, debtManagement: 0, budgeting: 8 },
        response: "Scarcity is designed to make you decide fast. Deciding on your own terms, even slowly, is the win.",
      },
      {
        id: "c",
        label: "Buy a cheaper alternative pair",
        emoji: "🥾",
        cost: 45,
        isGrannyPick: false,
        effects: { savingsDiscipline: 2, impulseControl: 2, debtManagement: 0, budgeting: 2 },
        response: "A reasonable middle ground — you got new trainers without chasing the hype price.",
      },
    ],
  },
  {
    id: "s020-coffee-habit",
    category: "impulse",
    difficulty: "easy",
    setupLine: "You've got £45 left until payday, six days away.",
    situation: "It's your third coffee-shop stop this week, and it's becoming a daily thing.",
    choices: [
      {
        id: "a",
        label: "Buy today's coffee as usual",
        emoji: "☕",
        cost: 4,
        isGrannyPick: false,
        effects: { savingsDiscipline: -2, impulseControl: -2, debtManagement: 0, budgeting: -2 },
        response: "One coffee's never the issue. It's whether you notice it's become six a week without deciding that on purpose.",
      },
      {
        id: "b",
        label: "Make coffee at home today",
        emoji: "🏠",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 6, debtManagement: 0, budgeting: 6 },
        response: "A small swap, but the kind that adds up quietly over a month — in a good way this time.",
      },
      {
        id: "c",
        label: "Buy it, but skip the extra syrup shot",
        emoji: "🥤",
        cost: 3,
        isGrannyPick: false,
        effects: { savingsDiscipline: 2, impulseControl: 2, debtManagement: 0, budgeting: 2 },
        response: "A fair compromise if the coffee stop itself is part of your day, not just the coffee.",
      },
    ],
  },
  {
    id: "s021-unread-books",
    category: "impulse",
    difficulty: "easy",
    setupLine: "You've got £100 left this month.",
    situation: "You spot a book that looks interesting — you've got four unread ones at home already.",
    choices: [
      {
        id: "a",
        label: "Buy it anyway",
        emoji: "📚",
        cost: 12,
        isGrannyPick: false,
        effects: { savingsDiscipline: -2, impulseControl: -4, debtManagement: 0, budgeting: -2 },
        response: "A book's a fine thing to want. Four unread ones is a fine reason to ask whether it's reading you're after, or buying.",
      },
      {
        id: "b",
        label: "Borrow it from the library instead",
        emoji: "📖",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 8, debtManagement: 0, budgeting: 4 },
        response: "Same story, no cost, and one less thing added to the unread pile.",
      },
      {
        id: "c",
        label: "Add it to a list and read your existing four first",
        emoji: "📋",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 4, impulseControl: 6, debtManagement: 0, budgeting: 2 },
        response: "A fair compromise — you'll actually get to it once there's space on the shelf, literally and otherwise.",
      },
    ],
  },
  {
    id: "s022-gadget-discount",
    category: "impulse",
    difficulty: "medium",
    setupLine: "You've got £210 left this month.",
    situation: "A gadget you've mildly wanted for months is suddenly 30% off — but you weren't planning to buy it this month.",
    choices: [
      {
        id: "a",
        label: "Buy it now before the discount ends",
        emoji: "🎧",
        cost: 90,
        isGrannyPick: false,
        effects: { savingsDiscipline: -8, impulseControl: -6, debtManagement: 0, budgeting: -8 },
        response: "A real discount on something you'll definitely use is different from an excuse — the question is honestly which one this is.",
      },
      {
        id: "b",
        label: "Check if it's still wanted in a week",
        emoji: "🤔",
        cost: 90,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 8, debtManagement: 0, budgeting: 6 },
        response: "If it's still on your mind next week, that discount will likely still be findable somewhere. If it's not, you've saved the whole £90.",
      },
      {
        id: "c",
        label: "Skip it — it wasn't in this month's plan",
        emoji: "🚫",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 8, impulseControl: 6, debtManagement: 0, budgeting: 8 },
        response: "A fair call. A plan that bends for every good deal isn't really a plan.",
      },
    ],
  },
  {
    id: "s023-amazon-browse",
    category: "impulse",
    difficulty: "easy",
    setupLine: "You've got £65 left until payday, four days away.",
    situation: "You open a shopping app 'just to look' and twenty minutes later have a full basket.",
    choices: [
      {
        id: "a",
        label: "Check out the whole basket",
        emoji: "🛒",
        cost: 38,
        isGrannyPick: false,
        effects: { savingsDiscipline: -6, impulseControl: -10, debtManagement: 0, budgeting: -6 },
        response: "'Just looking' rarely stays just looking. Worth noticing how the basket filled up without a single decision being made on purpose.",
      },
      {
        id: "b",
        label: "Close the app, basket unpurchased",
        emoji: "❌",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 12, debtManagement: 0, budgeting: 6 },
        response: "Nothing in that basket was on your list an hour ago. It can wait until something is.",
      },
      {
        id: "c",
        label: "Buy just the one thing you actually needed",
        emoji: "✅",
        cost: 8,
        isGrannyPick: false,
        effects: { savingsDiscipline: 4, impulseControl: 6, debtManagement: 0, budgeting: 4 },
        response: "A sensible edit — you got what you came for and left the rest behind.",
      },
    ],
  },
  {
    id: "s024-credit-card-minimum",
    category: "debt",
    difficulty: "medium",
    setupLine: "You've got £220 left this month after essentials.",
    situation: "Your credit card bill has arrived. You can pay the minimum, or put more towards it.",
    choices: [
      {
        id: "a",
        label: "Pay the minimum, spend the rest",
        emoji: "💳",
        cost: 25,
        isGrannyPick: false,
        effects: { savingsDiscipline: -8, impulseControl: -4, debtManagement: -12, budgeting: -6 },
        response: "The minimum keeps the account happy, but the interest keeps quietly growing underneath. It's rarely the cheapest option in the end.",
      },
      {
        id: "b",
        label: "Pay as much extra as you can afford",
        emoji: "💪",
        cost: 150,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 6, debtManagement: 14, budgeting: 8 },
        response: "Every extra pound now is interest you don't pay later. This is the boring choice that actually works.",
      },
      {
        id: "c",
        label: "Pay half the balance",
        emoji: "🔀",
        cost: 90,
        isGrannyPick: false,
        effects: { savingsDiscipline: 2, impulseControl: 2, debtManagement: 6, budgeting: 4 },
        response: "A reasonable middle path — real progress, even if not the fastest possible.",
      },
    ],
  },
  {
    id: "s025-overdraft-creep",
    category: "debt",
    difficulty: "medium",
    setupLine: "Your current account has quietly slipped £180 into its overdraft this month.",
    situation: "You've noticed, and payday's a week away.",
    choices: [
      {
        id: "a",
        label: "Ignore it — it'll sort itself out on payday",
        emoji: "🙈",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: -8, impulseControl: -4, debtManagement: -10, budgeting: -8 },
        response: "It usually does sort itself out — right up until the month it doesn't. Worth checking the fees before assuming it's free.",
      },
      {
        id: "b",
        label: "Check the overdraft fees and make a plan to clear it",
        emoji: "📊",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 6, debtManagement: 12, budgeting: 8 },
        response: "Knowing the actual cost changes how urgent it feels. That's usually enough to make the plan itself easy.",
      },
      {
        id: "c",
        label: "Cut spending hard for the rest of the week",
        emoji: "✂️",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 6, impulseControl: 6, debtManagement: 8, budgeting: 6 },
        response: "A reasonable short-term fix — just make sure it's a one-off, not the whole strategy every month.",
      },
    ],
  },
  {
    id: "s026-buy-now-pay-later",
    category: "debt",
    difficulty: "medium",
    setupLine: "You've got £140 left this month.",
    situation: "A checkout offers 'buy now, pay later' — split into four instalments, no interest, for something you'd been eyeing at £160.",
    choices: [
      {
        id: "a",
        label: "Use it — it's interest-free, so why not",
        emoji: "🔀",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: -8, impulseControl: -10, debtManagement: -8, budgeting: -6 },
        response: "No interest doesn't mean no risk — it just means the cost of missing a payment is hidden further down the page. Worth reading before you tap.",
      },
      {
        id: "b",
        label: "Save up and buy it outright next month",
        emoji: "🐷",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 10, impulseControl: 8, debtManagement: 6, budgeting: 8 },
        response: "Slower, and a little less exciting — but you'll own it outright with nothing quietly tracking you for the next three months.",
      },
      {
        id: "c",
        label: "Skip it entirely",
        emoji: "🚫",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 6, impulseControl: 6, debtManagement: 4, budgeting: 6 },
        response: "If it wasn't essential, this is a perfectly fine answer too.",
      },
    ],
  },
  {
    id: "s027-payday-loan-offer",
    category: "debt",
    difficulty: "hard",
    setupLine: "You've got £15 left until payday, three days away, and an unexpected £60 bill just landed.",
    situation: "An app on your phone offers a quick £60 loan, 'approved in minutes'.",
    choices: [
      {
        id: "a",
        label: "Take the loan",
        emoji: "⚡",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: -12, impulseControl: -6, debtManagement: -14, budgeting: -10 },
        response: "Fast money is expensive money, almost always. I'd want to see every other door tried first.",
      },
      {
        id: "b",
        label: "Ask if the bill can wait three days",
        emoji: "📞",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 8, debtManagement: 10, budgeting: 8 },
        response: "Most bills have more flexibility than they let on, if you simply ask. Three days is nothing to them and everything to your wallet.",
      },
      {
        id: "c",
        label: "Cover it from a friend, pay back on payday",
        emoji: "🤝",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 2, impulseControl: 2, debtManagement: 2, budgeting: 2 },
        response: "Can work well if you're both clear on the terms — just put it in writing, even informally, so nobody's left guessing.",
      },
    ],
  },
  {
    id: "s028-friend-borrow",
    category: "debt",
    difficulty: "medium",
    setupLine: "You've got £90 spare this month, earmarked for savings.",
    situation: "A friend asks to borrow £60 until their payday, no clear date given.",
    choices: [
      {
        id: "a",
        label: "Hand it over, no questions",
        emoji: "💸",
        cost: 60,
        isGrannyPick: false,
        effects: { savingsDiscipline: -8, impulseControl: -4, debtManagement: 0, budgeting: -6 },
        response: "Generous, and I hope it comes back — just know that 'no clear date' is how good intentions quietly turn into gone money.",
      },
      {
        id: "b",
        label: "Lend it, but agree a repayment date first",
        emoji: "📅",
        cost: 60,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 6, debtManagement: 2, budgeting: 6 },
        response: "A date on it protects the money and the friendship both — awkward conversations now save worse ones later.",
      },
      {
        id: "c",
        label: "Say you can't this time",
        emoji: "🙅",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 8, impulseControl: 6, debtManagement: 0, budgeting: 8 },
        response: "A hard thing to say, but your savings goal doesn't stop mattering just because someone else needs help.",
      },
    ],
  },
  {
    id: "s029-store-card-offer",
    category: "debt",
    difficulty: "medium",
    setupLine: "You're at the till with £85 of shopping.",
    situation: "The cashier offers 20% off today if you sign up for the store card on the spot.",
    choices: [
      {
        id: "a",
        label: "Sign up for the discount",
        emoji: "💳",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: -6, impulseControl: -6, debtManagement: -8, budgeting: -4 },
        response: "Today's 20% off is real. So is the new credit line you didn't plan for, sitting in your wallet from tomorrow.",
      },
      {
        id: "b",
        label: "Decline and pay full price",
        emoji: "🙅",
        cost: 85,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 8, debtManagement: 8, budgeting: 6 },
        response: "A missed discount stings less than an account you didn't actually want, three months from now.",
      },
      {
        id: "c",
        label: "Ask if the discount applies without signing up",
        emoji: "❓",
        cost: 85,
        isGrannyPick: false,
        effects: { savingsDiscipline: 2, impulseControl: 4, debtManagement: 2, budgeting: 2 },
        response: "Worth asking — sometimes it does. Costs nothing to check before deciding.",
      },
    ],
  },
  {
    id: "s030-debt-consolidation",
    category: "debt",
    difficulty: "hard",
    setupLine: "You're carrying balances on two cards, totalling £1,200, at different interest rates.",
    situation: "A consolidation loan offer arrives — one single monthly payment at a lower combined rate.",
    choices: [
      {
        id: "a",
        label: "Take it without reading the terms closely",
        emoji: "✍️",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: -6, impulseControl: -4, debtManagement: -8, budgeting: -4 },
        response: "Consolidation can genuinely help — but only if the new rate and term are actually better, not just simpler to look at.",
      },
      {
        id: "b",
        label: "Compare the total cost against your current cards first",
        emoji: "🧮",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 6, debtManagement: 12, budgeting: 8 },
        response: "A few minutes of arithmetic here is worth more than the loan's whole marketing page. If the numbers hold up, it's a good move.",
      },
      {
        id: "c",
        label: "Leave the cards as they are",
        emoji: "⏸️",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 2, impulseControl: 2, debtManagement: 0, budgeting: 2 },
        response: "Not wrong, if the offer genuinely doesn't add up — just don't let 'I'll deal with it later' become the actual plan.",
      },
    ],
  },
  {
    id: "s031-ignore-bill-reminder",
    category: "debt",
    difficulty: "easy",
    setupLine: "You've got a bill reminder sitting unread for four days.",
    situation: "You keep meaning to check it but haven't opened it yet.",
    choices: [
      {
        id: "a",
        label: "Keep putting it off",
        emoji: "😬",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: -4, impulseControl: -2, debtManagement: -8, budgeting: -6 },
        response: "Unopened bills don't stop being due — they just stop being known. That's a worse position, not a safer one.",
      },
      {
        id: "b",
        label: "Open it now and deal with whatever it says",
        emoji: "📬",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 6, debtManagement: 8, budgeting: 8 },
        response: "Whatever it says, you now know — and knowing is the whole first step to handling it.",
      },
      {
        id: "c",
        label: "Ask someone to check it with you",
        emoji: "🤝",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 4, impulseControl: 4, debtManagement: 4, budgeting: 4 },
        response: "If bills feel overwhelming alone, that's a perfectly good way through it.",
      },
    ],
  },
  {
    id: "s032-car-finance-upgrade",
    category: "debt",
    difficulty: "hard",
    setupLine: "You're two years into a car finance deal with 18 months left.",
    situation: "The dealer offers to 'upgrade' you to a newer model for a slightly higher monthly payment.",
    choices: [
      {
        id: "a",
        label: "Take the upgrade",
        emoji: "🚗",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: -8, impulseControl: -6, debtManagement: -12, budgeting: -8 },
        response: "'Slightly higher' resets the clock on a deal you were 18 months from finishing. That's rarely as small a change as it sounds.",
      },
      {
        id: "b",
        label: "Stick with the current car and finish the deal",
        emoji: "✅",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 8, debtManagement: 12, budgeting: 8 },
        response: "Eighteen months from owning it outright is worth protecting. The new model will still be there once you actually do.",
      },
      {
        id: "c",
        label: "Ask for the full cost comparison in writing",
        emoji: "📄",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 4, impulseControl: 4, debtManagement: 6, budgeting: 4 },
        response: "A sensible ask — the real numbers on paper tend to look very different from the pitch.",
      },
    ],
  },
  {
    id: "s033-student-loan-overpay",
    category: "debt",
    difficulty: "medium",
    setupLine: "You've got an unexpected £200 spare this month.",
    situation: "You could put it towards your student loan, or spend it on something you've wanted.",
    choices: [
      {
        id: "a",
        label: "Spend it on the thing you've wanted",
        emoji: "🛍️",
        cost: 200,
        isGrannyPick: false,
        effects: { savingsDiscipline: -6, impulseControl: -2, debtManagement: -4, budgeting: -6 },
        response: "Not a wrong choice on its own — just be clear it's a choice, not something that happened to you.",
      },
      {
        id: "b",
        label: "Put it towards the loan",
        emoji: "📉",
        cost: 200,
        isGrannyPick: false,
        effects: { savingsDiscipline: 6, impulseControl: 4, debtManagement: 10, budgeting: 6 },
        response: "Depending on your loan type, overpaying isn't always the mathematically best move — but the instinct to use unexpected money deliberately is a good one either way.",
      },
      {
        id: "c",
        label: "Split it — some spent, some paid towards the loan",
        emoji: "⚖️",
        cost: 100,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 8, debtManagement: 8, budgeting: 8 },
        response: "You got a bit of both — some enjoyment now, some progress you'll thank yourself for later. That balance is usually the sustainable one.",
      },
    ],
  },
  {
    id: "s034-mot-failure",
    category: "emergency",
    difficulty: "medium",
    setupLine: "You've got £260 left this month.",
    situation: "Your car's failed its MOT — repairs needed to pass, quoted at £180.",
    choices: [
      {
        id: "a",
        label: "Get it fixed at the garage that did the MOT",
        emoji: "🔧",
        cost: 180,
        isGrannyPick: false,
        effects: { savingsDiscipline: -4, impulseControl: 0, debtManagement: 0, budgeting: -2 },
        response: "Convenient, and probably fine — just know the first quote isn't always the best one.",
      },
      {
        id: "b",
        label: "Get a second quote before deciding",
        emoji: "📋",
        cost: 150,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 6, debtManagement: 2, budgeting: 8 },
        response: "A second quote took ten minutes and saved £30. That's a good hourly rate for a phone call.",
      },
      {
        id: "c",
        label: "Delay the repair",
        emoji: "⏸️",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: -6, impulseControl: -2, debtManagement: -4, budgeting: -4 },
        response: "A failed MOT usually means the car shouldn't really be driven — delaying tends to cost more, one way or another.",
      },
    ],
  },
  {
    id: "s035-boiler-breaks",
    category: "emergency",
    difficulty: "hard",
    setupLine: "You've got £310 left this month, mid-winter.",
    situation: "Your boiler's stopped working. A callout quote comes in at £120, with the possibility of a bigger repair on top.",
    choices: [
      {
        id: "a",
        label: "Book the callout straight away",
        emoji: "🔥",
        cost: 120,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 6, debtManagement: 2, budgeting: 8 },
        response: "Heating in winter isn't optional, and waiting rarely makes a boiler cheaper to fix. This is exactly what an emergency fund is for.",
      },
      {
        id: "b",
        label: "Try to fix it yourself first",
        emoji: "🛠️",
        cost: 20,
        isGrannyPick: false,
        effects: { savingsDiscipline: 2, impulseControl: 0, debtManagement: 0, budgeting: 0 },
        response: "Worth a look if you genuinely know what you're doing — just don't let pride turn a £120 fix into a £400 one.",
      },
      {
        id: "c",
        label: "Wrap up warm and put it off",
        emoji: "🧣",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: -6, impulseControl: -2, debtManagement: -2, budgeting: -4 },
        response: "A cold house in winter isn't a saving, it's a delay — and small boiler faults rarely improve by being ignored.",
      },
    ],
  },
  {
    id: "s036-phone-screen",
    category: "emergency",
    difficulty: "medium",
    setupLine: "You've got £150 left this month.",
    situation: "You've dropped your phone and cracked the screen. It still works, but it's hard to read.",
    choices: [
      {
        id: "a",
        label: "Book the official repair immediately",
        emoji: "📱",
        cost: 130,
        isGrannyPick: false,
        effects: { savingsDiscipline: -4, impulseControl: 0, debtManagement: 0, budgeting: -4 },
        response: "The official repair is safest, but rarely the cheapest option available — worth a quick check first.",
      },
      {
        id: "b",
        label: "Get a quote from an independent repair shop",
        emoji: "🔧",
        cost: 45,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 6, debtManagement: 0, budgeting: 8 },
        response: "Same working phone, a fraction of the cost. A crack in the glass didn't need the most expensive fix available.",
      },
      {
        id: "c",
        label: "Use a screen protector and leave it",
        emoji: "🩹",
        cost: 5,
        isGrannyPick: false,
        effects: { savingsDiscipline: 4, impulseControl: 4, debtManagement: 0, budgeting: 2 },
        response: "A fair stopgap if it's genuinely still usable — just don't let 'stopgap' quietly become permanent if it gets worse.",
      },
    ],
  },
  {
    id: "s037-vet-bill",
    category: "emergency",
    difficulty: "hard",
    setupLine: "You've got £180 left this month.",
    situation: "Your pet's unwell and needs a vet visit — likely £90 for the consultation, possibly more.",
    choices: [
      {
        id: "a",
        label: "Book the vet straight away",
        emoji: "🐾",
        cost: 90,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 6, debtManagement: 2, budgeting: 6 },
        response: "Not a choice really, is it — their health comes first. Just ask about payment options if the follow-up cost turns out bigger than expected.",
      },
      {
        id: "b",
        label: "Wait a day or two to see if it improves",
        emoji: "⏳",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: -4, impulseControl: 0, debtManagement: 0, budgeting: 0 },
        response: "Sometimes reasonable for something minor — just don't let cost be the reason you wait, if you're genuinely worried.",
      },
      {
        id: "c",
        label: "Ask the vet about a payment plan upfront",
        emoji: "📋",
        cost: 90,
        isGrannyPick: false,
        effects: { savingsDiscipline: 6, impulseControl: 6, debtManagement: 6, budgeting: 6 },
        response: "A sensible question to ask before the bill arrives, not after. Most practices have more flexibility than people assume.",
      },
    ],
  },
  {
    id: "s038-laptop-dies",
    category: "emergency",
    difficulty: "medium",
    setupLine: "You've got £220 left this month, and a work deadline tomorrow.",
    situation: "Your laptop's just died and you need it working tonight.",
    choices: [
      {
        id: "a",
        label: "Buy a new laptop tonight",
        emoji: "💻",
        cost: 220,
        isGrannyPick: false,
        effects: { savingsDiscipline: -10, impulseControl: -6, debtManagement: 0, budgeting: -8 },
        response: "A real emergency, but a full new laptop bought under deadline pressure rarely gets the best price or the best fit.",
      },
      {
        id: "b",
        label: "Borrow one to get through tomorrow, shop properly after",
        emoji: "🤝",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 8, debtManagement: 0, budgeting: 8 },
        response: "Solved tonight's actual problem without a panic purchase. Now you can shop for the laptop with a clear head, not a deadline.",
      },
      {
        id: "c",
        label: "Pay for express repair",
        emoji: "🔧",
        cost: 80,
        isGrannyPick: false,
        effects: { savingsDiscipline: 2, impulseControl: 2, debtManagement: 0, budgeting: 2 },
        response: "Reasonable if it's genuinely fixable — just get a diagnosis before committing to the 'express' price.",
      },
    ],
  },
  {
    id: "s039-flat-tyre",
    category: "emergency",
    difficulty: "easy",
    setupLine: "You've got £70 left until payday, five days away.",
    situation: "You've got a flat tyre on the way to work.",
    choices: [
      {
        id: "a",
        label: "Call roadside assistance if you have cover",
        emoji: "📞",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 4, debtManagement: 0, budgeting: 6 },
        response: "If you're already paying for cover, this is exactly what it's for — use what you've already bought.",
      },
      {
        id: "b",
        label: "Pay a garage to sort it there and then",
        emoji: "🔧",
        cost: 45,
        isGrannyPick: false,
        effects: { savingsDiscipline: -4, impulseControl: 0, debtManagement: 0, budgeting: -4 },
        response: "Gets you moving fastest — just know it's usually the most expensive way to solve a flat tyre.",
      },
      {
        id: "c",
        label: "Change it yourself if you're able",
        emoji: "🛠️",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 6, impulseControl: 4, debtManagement: 0, budgeting: 4 },
        response: "Free and quick, if you know how. A genuinely useful skill to have either way.",
      },
    ],
  },
  {
    id: "s040-broken-glasses",
    category: "emergency",
    difficulty: "medium",
    setupLine: "You've got £160 left this month.",
    situation: "Your glasses have snapped and you can't see well without them.",
    choices: [
      {
        id: "a",
        label: "Buy the first replacement pair you see",
        emoji: "👓",
        cost: 140,
        isGrannyPick: false,
        effects: { savingsDiscipline: -6, impulseControl: -4, debtManagement: 0, budgeting: -6 },
        response: "Understandable when you can't see straight — just know opticians vary a lot in price for the same prescription.",
      },
      {
        id: "b",
        label: "Check if they can be repaired first",
        emoji: "🔧",
        cost: 20,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 6, debtManagement: 0, budgeting: 8 },
        response: "A repair, if possible, solves the actual problem for a fraction of a new pair. Always worth asking first.",
      },
      {
        id: "c",
        label: "Use an old prescription pair in the meantime",
        emoji: "👀",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 6, impulseControl: 6, debtManagement: 0, budgeting: 4 },
        response: "Not perfect, but a sensible stopgap that buys you time to shop properly, not urgently.",
      },
    ],
  },
  {
    id: "s041-roof-leak",
    category: "emergency",
    difficulty: "hard",
    setupLine: "You've got £340 left this month.",
    situation: "You've spotted a leak in the roof after heavy rain.",
    choices: [
      {
        id: "a",
        label: "Book a full roof repair immediately, whatever it costs",
        emoji: "🏠",
        cost: 340,
        isGrannyPick: false,
        effects: { savingsDiscipline: -8, impulseControl: 0, debtManagement: -4, budgeting: -8 },
        response: "Leaks shouldn't be ignored, that's true — but the first quote, paid in full without comparison, isn't the only responsible option.",
      },
      {
        id: "b",
        label: "Get a temporary fix and quotes for the full repair",
        emoji: "🪣",
        cost: 60,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 6, debtManagement: 2, budgeting: 8 },
        response: "Stopped the damage getting worse today, and gives you room to choose the right repair properly, not under pressure.",
      },
      {
        id: "c",
        label: "Wait until next month to deal with it",
        emoji: "⏸️",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: -8, impulseControl: -2, debtManagement: -4, budgeting: -6 },
        response: "Water damage rarely waits politely for a more convenient month. This is usually the more expensive choice in the end.",
      },
    ],
  },
  {
    id: "s042-lost-wallet",
    category: "emergency",
    difficulty: "medium",
    setupLine: "You've got £95 left until payday.",
    situation: "You've lost your wallet — cards, some cash, ID all gone.",
    choices: [
      {
        id: "a",
        label: "Order rush replacements for everything",
        emoji: "⚡",
        cost: 40,
        isGrannyPick: false,
        effects: { savingsDiscipline: -4, impulseControl: 0, debtManagement: 0, budgeting: -4 },
        response: "Understandable panic — just check which replacements are genuinely urgent versus which can wait for standard, free delivery.",
      },
      {
        id: "b",
        label: "Cancel cards immediately, replace ID at standard speed",
        emoji: "🪪",
        cost: 10,
        isGrannyPick: true,
        effects: { savingsDiscipline: 6, impulseControl: 6, debtManagement: 2, budgeting: 6 },
        response: "The urgent bit — stopping anyone else using your cards — done straight away. Everything else can wait for the free option.",
      },
      {
        id: "c",
        label: "Wait a day in case it turns up",
        emoji: "⏳",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: -6, impulseControl: 0, debtManagement: -2, budgeting: -2 },
        response: "Hope is nice, but cards left active are a real risk in the meantime. I'd cancel first and hope second.",
      },
    ],
  },
  {
    id: "s043-prescription-cost",
    category: "emergency",
    difficulty: "easy",
    setupLine: "You've got £55 left until payday, four days away.",
    situation: "You need a prescription filled that costs more than expected.",
    choices: [
      {
        id: "a",
        label: "Pay it, whatever the cost",
        emoji: "💊",
        cost: 25,
        isGrannyPick: true,
        effects: { savingsDiscipline: 4, impulseControl: 4, debtManagement: 0, budgeting: 4 },
        response: "Health isn't the place to economise. This one's simply not optional.",
      },
      {
        id: "b",
        label: "Ask the pharmacist about a cheaper generic version",
        emoji: "💬",
        cost: 12,
        isGrannyPick: false,
        effects: { savingsDiscipline: 6, impulseControl: 4, debtManagement: 0, budgeting: 6 },
        response: "A perfectly sensible question — often the exact same medicine, genuinely cheaper, just under a different name.",
      },
      {
        id: "c",
        label: "Skip it to save money",
        emoji: "🚫",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: -10, impulseControl: -6, debtManagement: 0, budgeting: -8 },
        response: "Please don't skip medicine over money — that's the one place worth finding another way, even if it means asking for help.",
      },
    ],
  },
  {
    id: "s044-tax-refund",
    category: "savings",
    difficulty: "easy",
    setupLine: "A £340 tax refund has just landed in your account, unexpectedly.",
    situation: "It wasn't budgeted for — entirely free money, from your perspective.",
    choices: [
      {
        id: "a",
        label: "Spend it on something fun",
        emoji: "🎉",
        cost: 340,
        isGrannyPick: false,
        effects: { savingsDiscipline: -8, impulseControl: -4, debtManagement: 0, budgeting: -4 },
        response: "It's genuinely yours to enjoy — just notice 'unexpected money' has a way of vanishing faster than money you worked for.",
      },
      {
        id: "b",
        label: "Put it all towards savings or debt",
        emoji: "🏦",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 14, impulseControl: 6, debtManagement: 8, budgeting: 8 },
        response: "Money you weren't relying on is the easiest money to build a future with — you won't even miss it.",
      },
      {
        id: "c",
        label: "Split it — some saved, some spent",
        emoji: "⚖️",
        cost: 170,
        isGrannyPick: false,
        effects: { savingsDiscipline: 8, impulseControl: 6, debtManagement: 4, budgeting: 6 },
        response: "A very sensible balance — you get to enjoy some of the windfall and still make real progress with the rest.",
      },
    ],
  },
  {
    id: "s045-work-bonus",
    category: "savings",
    difficulty: "medium",
    setupLine: "You've just received a £500 work bonus.",
    situation: "It wasn't guaranteed, and you're deciding what to do with it.",
    choices: [
      {
        id: "a",
        label: "Treat yourself to something big",
        emoji: "🎁",
        cost: 500,
        isGrannyPick: false,
        effects: { savingsDiscipline: -10, impulseControl: -4, debtManagement: 0, budgeting: -6 },
        response: "You earned it, genuinely — just be honest that a £500 spend and a £500 saving feel very different a year from now.",
      },
      {
        id: "b",
        label: "Put it entirely towards a savings goal",
        emoji: "🎯",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 14, impulseControl: 6, debtManagement: 4, budgeting: 10 },
        response: "A bonus is the best kind of money to build a goal with — you weren't counting on it, so you won't feel its absence.",
      },
      {
        id: "c",
        label: "Treat yourself modestly, save the rest",
        emoji: "🎈",
        cost: 100,
        isGrannyPick: false,
        effects: { savingsDiscipline: 8, impulseControl: 6, debtManagement: 2, budgeting: 6 },
        response: "A small celebration and real progress, both at once. A perfectly sustainable way to handle good news.",
      },
    ],
  },
  {
    id: "s046-found-money",
    category: "savings",
    difficulty: "easy",
    setupLine: "You've found a £20 note in an old coat pocket.",
    situation: "Genuinely forgotten money, found by surprise.",
    choices: [
      {
        id: "a",
        label: "Spend it straight away, no plan",
        emoji: "💸",
        cost: 20,
        isGrannyPick: false,
        effects: { savingsDiscipline: -2, impulseControl: -2, debtManagement: 0, budgeting: 0 },
        response: "Small and harmless, honestly — money like this rarely makes or breaks a month either way.",
      },
      {
        id: "b",
        label: "Put it straight into savings",
        emoji: "🐖",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 4, debtManagement: 0, budgeting: 4 },
        response: "Forgotten money is the easiest money to save — you'd already forgotten it existed, so you won't miss it now either.",
      },
      {
        id: "c",
        label: "Buy a small treat with it",
        emoji: "🍫",
        cost: 20,
        isGrannyPick: false,
        effects: { savingsDiscipline: 0, impulseControl: 0, debtManagement: 0, budgeting: 0 },
        response: "A perfectly fine use for a genuinely unplanned £20. Small joys don't need justifying.",
      },
    ],
  },
  {
    id: "s047-pay-rise",
    category: "savings",
    difficulty: "medium",
    setupLine: "You've just been given a pay rise — an extra £120 a month, going forward.",
    situation: "It's the first payday it's landed.",
    choices: [
      {
        id: "a",
        label: "Let your spending quietly rise to match it",
        emoji: "📈",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: -8, impulseControl: -4, debtManagement: 0, budgeting: -6 },
        response: "This is how a pay rise disappears without a trace — spending expands to fill it before you've decided anything on purpose.",
      },
      {
        id: "b",
        label: "Set up an automatic transfer for the extra amount",
        emoji: "🔁",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 14, impulseControl: 6, debtManagement: 2, budgeting: 10 },
        response: "Moving it before you see it means you never adjust your lifestyle to money you never actually held. This is how real progress gets made quietly.",
      },
      {
        id: "c",
        label: "Decide deliberately to spend half, save half",
        emoji: "⚖️",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 8, impulseControl: 6, debtManagement: 2, budgeting: 6 },
        response: "A conscious choice either way beats a spending increase nobody decided on. This is a fine version of that choice.",
      },
    ],
  },
  {
    id: "s048-cashback-reward",
    category: "savings",
    difficulty: "easy",
    setupLine: "You've earned £30 in cashback rewards, sitting in your account.",
    situation: "It's real money, just from a different source than usual.",
    choices: [
      {
        id: "a",
        label: "Spend it as if it doesn't quite count",
        emoji: "🛍️",
        cost: 30,
        isGrannyPick: false,
        effects: { savingsDiscipline: -4, impulseControl: -2, debtManagement: 0, budgeting: 0 },
        response: "It counts exactly as much as any other £30 — worth treating it that way, even if it arrived differently.",
      },
      {
        id: "b",
        label: "Move it straight into your savings goal",
        emoji: "🎯",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 10, impulseControl: 4, debtManagement: 0, budgeting: 6 },
        response: "Rewards money moved on purpose adds up the same as any other saving — quietly, and faster than you'd think.",
      },
      {
        id: "c",
        label: "Leave it where it landed",
        emoji: "🤷",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 2, impulseControl: 2, debtManagement: 0, budgeting: 0 },
        response: "Not wrong, though money without a job tends to get spent on whatever's nearest. Worth giving it one, even a small one.",
      },
    ],
  },
  {
    id: "s049-sell-furniture",
    category: "savings",
    difficulty: "easy",
    setupLine: "You've sold some old furniture online for £85.",
    situation: "Unplanned money from clearing out things you no longer needed.",
    choices: [
      {
        id: "a",
        label: "Spend it on something new",
        emoji: "🛋️",
        cost: 85,
        isGrannyPick: false,
        effects: { savingsDiscipline: -4, impulseControl: -2, debtManagement: 0, budgeting: 0 },
        response: "A fair reward for the effort of selling it — just notice if 'clearing clutter' quietly becomes 'making room for more'.",
      },
      {
        id: "b",
        label: "Put it towards your savings goal",
        emoji: "💰",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 10, impulseControl: 4, debtManagement: 0, budgeting: 6 },
        response: "Turning things you didn't need into progress towards something you do — that's a genuinely good trade.",
      },
      {
        id: "c",
        label: "Split it between a treat and savings",
        emoji: "⚖️",
        cost: 40,
        isGrannyPick: false,
        effects: { savingsDiscipline: 6, impulseControl: 4, debtManagement: 0, budgeting: 4 },
        response: "A sensible middle path — you enjoyed some of the win and kept some of it working for you.",
      },
    ],
  },
  {
    id: "s050-cancel-subscription",
    category: "savings",
    difficulty: "easy",
    setupLine: "You've noticed a £9.99/month subscription you haven't used in three months.",
    situation: "It's easy to keep, and easy to cancel.",
    choices: [
      {
        id: "a",
        label: "Keep it — might use it again",
        emoji: "🤷",
        cost: 10,
        isGrannyPick: false,
        effects: { savingsDiscipline: -4, impulseControl: -2, debtManagement: 0, budgeting: -4 },
        response: "'Might use it again' is doing a lot of work here — three unused months is usually a fairly honest answer already.",
      },
      {
        id: "b",
        label: "Cancel it today",
        emoji: "✂️",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 10, impulseControl: 6, debtManagement: 0, budgeting: 8 },
        response: "£120 a year, for something you weren't using. You can always resubscribe the day you actually need it again.",
      },
      {
        id: "c",
        label: "Downgrade to a cheaper tier instead",
        emoji: "🔽",
        cost: 5,
        isGrannyPick: false,
        effects: { savingsDiscipline: 4, impulseControl: 4, debtManagement: 0, budgeting: 4 },
        response: "A reasonable middle ground if there's a part of it you do still use.",
      },
    ],
  },
  {
    id: "s051-roundup-savings",
    category: "savings",
    difficulty: "easy",
    setupLine: "Your bank offers a 'round up every purchase to the nearest pound' savings feature.",
    situation: "You're deciding whether to switch it on.",
    choices: [
      {
        id: "a",
        label: "Turn it on",
        emoji: "✅",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 2, debtManagement: 0, budgeting: 6 },
        response: "Small and automatic is exactly how good saving habits survive a busy month — you won't even notice it happening.",
      },
      {
        id: "b",
        label: "Ignore it — spare change won't add up to much",
        emoji: "🤷",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: -2, impulseControl: 0, debtManagement: 0, budgeting: 0 },
        response: "Fair, if you'd rather save on purpose than by accident — just know these small pots do add up more than people expect.",
      },
      {
        id: "c",
        label: "Turn it on, but set the roundup higher",
        emoji: "📈",
        cost: 0,
        isGrannyPick: false,
        effects: { savingsDiscipline: 6, impulseControl: 2, debtManagement: 0, budgeting: 4 },
        response: "A bit more ambitious — worth trying for a month to see if you notice it in your day-to-day spending.",
      },
    ],
  },
  {
    id: "s052-no-spend-weekend",
    category: "savings",
    difficulty: "medium",
    setupLine: "It's Friday evening, and you've decided to try a no-spend weekend.",
    situation: "Saturday morning, and a friend suggests brunch out.",
    choices: [
      {
        id: "a",
        label: "Break the no-spend plan for brunch",
        emoji: "🥞",
        cost: 18,
        isGrannyPick: false,
        effects: { savingsDiscipline: -4, impulseControl: -4, debtManagement: 0, budgeting: -2 },
        response: "One brunch won't undo much — just notice how quickly a plan gets talked out of, given the chance.",
      },
      {
        id: "b",
        label: "Suggest a free alternative — a walk, coffee at home first",
        emoji: "🚶",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 8, impulseControl: 8, debtManagement: 0, budgeting: 6 },
        response: "You kept the friendship and the plan both. That's the actual skill here, not just saying no.",
      },
      {
        id: "c",
        label: "Go, but keep the order small",
        emoji: "🥐",
        cost: 6,
        isGrannyPick: false,
        effects: { savingsDiscipline: 2, impulseControl: 4, debtManagement: 0, budgeting: 2 },
        response: "A fair compromise if the company mattered more than the challenge itself.",
      },
    ],
  },
  {
    id: "s053-freelance-income",
    category: "savings",
    difficulty: "medium",
    setupLine: "A bit of freelance work brought in an extra £150 this month.",
    situation: "Money outside your normal income, with no fixed job yet.",
    choices: [
      {
        id: "a",
        label: "Treat it as normal spending money",
        emoji: "💳",
        cost: 150,
        isGrannyPick: false,
        effects: { savingsDiscipline: -6, impulseControl: -2, debtManagement: 0, budgeting: -4 },
        response: "You can, of course — just know that money outside your normal budget is the easiest kind to build something real with, precisely because you weren't relying on it.",
      },
      {
        id: "b",
        label: "Set it aside for taxes and savings",
        emoji: "📊",
        cost: 0,
        isGrannyPick: true,
        effects: { savingsDiscipline: 12, impulseControl: 6, debtManagement: 4, budgeting: 10 },
        response: "Freelance income needs a bit more discipline than a payslip does — putting some aside now means no unpleasant surprise later.",
      },
      {
        id: "c",
        label: "Put half towards a goal, spend the rest",
        emoji: "⚖️",
        cost: 75,
        isGrannyPick: false,
        effects: { savingsDiscipline: 8, impulseControl: 6, debtManagement: 2, budgeting: 6 },
        response: "A sound split — real progress made, and a bit of the extra effort enjoyed too.",
      },
    ],
  },

  // Add new scenarios below, following the shape above. No other code
  // needs to change when the bank grows.
];

/**
 * Deterministic "scenario of the day" — every visitor on the same calendar
 * date sees the same dilemma, no server call or randomness needed.
 * Swap SCENARIOS for a larger pool as the bank grows; nothing else changes.
 */
export function getScenarioForDate(
  date: Date,
  pool: GrannyScenario[] = SCENARIOS,
): GrannyScenario {
  const start = Date.UTC(date.getUTCFullYear(), 0, 0);
  const diff = Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()) - start;
  const dayOfYear = Math.floor(diff / 86_400_000);
  return pool[dayOfYear % pool.length];
}
